### ISSUE TITLE
RTP topologies

### ISSUE THREAD

**Issue by aboba** [alvestrand/id-abs-capture-timestamp#2]
Section 1

"However, when multiple hops and multiple systems are involved, this task becomes more difficult; in particular, when one desires to synchronize media from multiple sources with independent clocks, where the media may have traveled over multiple network hops between the source and destination.This memo describes one mechanism for providing more information to make such synchronization possible."

[BA]  Is the sole use case for this document "lip sync" from a single source?  Or are other use cases possible too (e.g. synchronized concert)?

As written, this section could be interpreted to apply to a wide range of RTP topologies described in RFC 7667. Since RTCP termination is mentioned in Section 3, this does not appear to be the intent.  I'd suggest adding a paragraph describing the RTP topologies to which this specification applies (e.g. Section 3.6 and 3.7 of RFC 7667)

Section 3.1.2.1

" Absolute capture timestamp is the NTP timestamp of when the first frame in a packet was originally captured. This timestamp MUST be based on the same clock as the clock used to generate NTP timestamps for RTCP sender reports on the capture system."

[BA] Does this imply that the RTCP SR NTP timestamp from the capturing system is placed in this field?

Section 3.1.2.2

   Estimated capture clock offset is the sender's estimate of the offset
   between its own NTP clock and the capture system's NTP clock.  The
   sender is here defined as the system that owns the NTP clock used to
   generate the NTP timestamps for the RTCP sender reports on this
   stream.  The sender system is typically either the capture system or
   a mixer.

[BA] In an RTCP-terminating topology wouldn't the mixer/SFM be the sender?  In what topology would the capture system be the sender?

Section 3.1.3.2

   An intermediate system (e.g. mixer) MAY adjust these timestamps as
   needed.  It MAY also choose to rewrite the timestamps completely,
   using its own NTP clock as reference clock, if it wants to present
   itself as a capture system for A/V-sync purposes.

[BA] Wouldn't this behavior be governed by the topology? For example, an RTCP-terminating middle box uses its own NTP clock, but presumably a translator would not.

**Comment by alvestrand** [comment]
> Section 1
> 
> "However, when multiple hops and multiple systems are involved, this task becomes more difficult; in particular, when one desires to synchronize media from multiple sources with independent clocks, where the media may have traveled over multiple network hops between the source and destination.This memo describes one mechanism for providing more information to make such synchronization possible."
> 
> [BA] Is the sole use case for this document "lip sync" from a single source? Or are other use cases possible too (e.g. synchronized concert)?

It's been envisaged for synchronizing audio and video from multiple independent sources, for instance from multiple microphones on independent systems in the same room.

The other prominent use case is statistics on end-to-end delay; for this use case, the fact that the estimates will be wrong some of the time doesn't matter as long as they're mostly correct most of the time.

> 
> As written, this section could be interpreted to apply to a wide range of RTP topologies described in RFC 7667. Since RTCP termination is mentioned in Section 3, this does not appear to be the intent. I'd suggest adding a paragraph describing the RTP topologies to which this specification applies (e.g. Section 3.6 and 3.7 of RFC 7667)

The main scenario supported is an RTP-terminating mixer (3.6, 3.9).
I'll have to scratch my head a bit about what will happen in other scenarios.

> Section 3.1.2.1
> 
> " Absolute capture timestamp is the NTP timestamp of when the first frame in a packet was originally captured. This timestamp MUST be based on the same clock as the clock used to generate NTP timestamps for RTCP sender reports on the capture system."
> 
> [BA] Does this imply that the RTCP SR NTP timestamp from the capturing system is placed in this field?

No. If they originate from the same clock, the offset field from the originating system will be zero.
However, the RTCP SR NTP timestamp is produced when the RTCP SR is sent, not when the frame is captured.

> 
> Section 3.1.2.2
> 
> Estimated capture clock offset is the sender's estimate of the offset between its own NTP clock and the capture system's NTP clock. The sender is here defined as the system that owns the NTP clock used to generate the NTP timestamps for the RTCP sender reports on this stream. The sender system is typically either the capture system or a mixer.
> 
> [BA] In an RTCP-terminating topology wouldn't the mixer/SFM be the sender? In what topology would the capture system be the sender?

Point-to-point and point-to-multipoint (RFC  7667 3.1, 3.2, 3.4, 3.7) are the obvious ones. As long as the delay estimation algorithm runs between the capture system and the consumer system. In all RTCP-terminating topologies, the middle box is the sender.
> 
> Section 3.1.3.2
> 
> An intermediate system (e.g. mixer) MAY adjust these timestamps as needed. It MAY also choose to rewrite the timestamps completely, using its own NTP clock as reference clock, if it wants to present itself as a capture system for A/V-sync purposes.
> 
> [BA] Wouldn't this behavior be governed by the topology? For example, an RTCP-terminating middle box uses its own NTP clock, but presumably a translator would not.

Right. See above. Would be good to say "An intermediate RTCP-terminating system" instead of just "an intermediate system", for clarity.

**Comment by Arctunix** [comment]
> > Section 1
> > "However, when multiple hops and multiple systems are involved, this task becomes more difficult; in particular, when one desires to synchronize media from multiple sources with independent clocks, where the media may have traveled over multiple network hops between the source and destination.This memo describes one mechanism for providing more information to make such synchronization possible."
> > [BA] Is the sole use case for this document "lip sync" from a single source? Or are other use cases possible too (e.g. synchronized concert)?
> 
> It's been envisaged for synchronizing audio and video from multiple independent sources, for instance from multiple microphones on independent systems in the same room.

There are two separate ways to accomplish lip sync using abs-capture-time:

1) Take the "absolute capture timestamp" associated with each audio and media frame and sync according to that. This has perfect accuracy but only works if the audio and media was originally captured and timestamped on the same system.

2) For each audio and media frame, calculate the one-way delay from capture to receiver using both "absolute capture timestamp" and "estimated capture clock offset". Lip sync based on one-way delay. This works across multiple capture systems (e.g. synchronized concerts) but is less accurate as it involves a series of clock offset calculations on each RTCP-terminating hop.

> > As written, this section could be interpreted to apply to a wide range of RTP topologies described in RFC 7667. Since RTCP termination is mentioned in Section 3, this does not appear to be the intent. I'd suggest adding a paragraph describing the RTP topologies to which this specification applies (e.g. Section 3.6 and 3.7 of RFC 7667)
> 
> The main scenario supported is an RTP-terminating mixer (3.6, 3.9). I'll have to scratch my head a bit about what will happen in other scenarios.

The core principle is that RTCP-terminating endpoints must either a) update "estimated capture clock offset" or b) remove "estimated capture clock offset" if it resends the media frame to the next hop. The "absolute capture timestamp" part should be resent as-is (or maybe _slightly_ adjusted - see further down).

Endpoints that do not terminate RTCP should forward the abs-capture-time header extension as-is.

> > Section 3.1.3.2
> > An intermediate system (e.g. mixer) MAY adjust these timestamps as needed. It MAY also choose to rewrite the timestamps completely, using its own NTP clock as reference clock, if it wants to present itself as a capture system for A/V-sync purposes.
> > [BA] Wouldn't this behavior be governed by the topology? For example, an RTCP-terminating middle box uses its own NTP clock, but presumably a translator would not.
> 
> Right. See above. Would be good to say "An intermediate RTCP-terminating system" instead of just "an intermediate system", for clarity.

I think we've accidentally mixed different concepts up in this section:

1) An intermediate RTCP-terminating system MUST either a) update "estimated capture clock offset" or b) remove "estimated capture clock offset" when it resends a media frame since the RTCP-terminating system ahs its own NTP clock. Translators typically don't change the NTP clock so they should forward the offset as-is.

2) An intermediate system (both RTCP-terminating and non-terminating ones) may want to rewrite the timestamps for other reasons. We could for example have an audio transcoder as the intermediate system. The transcoding step will likely "shift" the timestamps a bit (e.g. add 3 ms of audio latency due to internal buffers in audio codecs). Adjustments to "absolute capture timestamp" are then needed, which is the purpose of this sentence: "An intermediate system (e.g. mixer) MAY adjust these timestamps as needed."

3) An intermediate system may also want to "pretend" that it's the capture system. A highly complex mixer could for example take multiple audio and video streams and do lip sync and other fancy things in the mixer. So that's where this sentence comes in: "It MAY also choose to rewrite the timestamps completely, using its own NTP clock as reference clock, if it wants to present itself as a capture system for A/V-sync purposes."

Confusing! :-)
